{
 "title": "Cpp vs Rust",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Client Request Latency (p99)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(tester_request_duration_seconds_bucket{container=\"cpp-client\", status=\"200\"}[30s])) by (le, container))",
     "legendFormat": "CPP"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(tester_request_duration_seconds_bucket{container=\"rust-client\", status=\"200\"}[30s])) by (le, container))",
     "legendFormat": "Rust"
    }
   ]
  },
  {
   "title": "Requests Per Second (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(tester_request_duration_seconds_count{status=\"200\", job=\"monitoring/cpp-client\"}[30s]))",
     "legendFormat": "CPP"
    },
    {
     "expr": "sum(rate(tester_request_duration_seconds_count{status=\"200\", job=\"monitoring/rust-client\"}[30s]))",
     "legendFormat": "Rust"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(sum(\n    rate(container_cpu_usage_seconds_total{container_label_io_kubernetes_container_name=\"cpp-app\"}[30s]))\nby (\n    container_label_io_kubernetes_pod_name, container_label_io_kubernetes_container_name) /\nsum(\n    container_spec_cpu_quota{container_label_io_kubernetes_container_name=\"cpp-app\"} /\n    container_spec_cpu_period{container_label_io_kubernetes_container_name=\"cpp-app\"}\n    ) \nby (container_label_io_kubernetes_pod_name, container_label_io_kubernetes_container_name))",
     "legendFormat": "CPP"
    },
    {
     "expr": "avg(sum(\n    rate(container_cpu_usage_seconds_total{container_label_io_kubernetes_container_name=\"rust-app\"}[30s]))\nby (\n    container_label_io_kubernetes_pod_name, container_label_io_kubernetes_container_name) /\nsum(\n    container_spec_cpu_quota{container_label_io_kubernetes_container_name=\"rust-app\"} /\n    container_spec_cpu_period{container_label_io_kubernetes_container_name=\"rust-app\"}\n    ) \nby (container_label_io_kubernetes_pod_name, container_label_io_kubernetes_container_name))",
     "legendFormat": "Rust"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(container_memory_working_set_bytes\n{\n    container_label_io_kubernetes_container_name=\"cpp-app\"\n} /\ncontainer_spec_memory_limit_bytes\n{\n    container_label_io_kubernetes_container_name=\"cpp-app\"\n})",
     "legendFormat": "CPP"
    },
    {
     "expr": "avg(container_memory_working_set_bytes\n{\n    container_label_io_kubernetes_container_name=\"rust-app\"\n} /\ncontainer_spec_memory_limit_bytes\n{\n    container_label_io_kubernetes_container_name=\"rust-app\"\n})",
     "legendFormat": "Rust"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n    rate(\n        tester_request_duration_seconds_count\n        {\n            container=~\"cpp-client\",\n            status!~\"[4-5].*\"\n        }[30s])) by (container) /\nsum(\n    rate(\n        tester_request_duration_seconds_count\n        {\n            container=~\"cpp-client\"\n        }[30s])) by (container)",
     "legendFormat": "CPP"
    },
    {
     "expr": "sum(\n    rate(\n        tester_request_duration_seconds_count\n        {\n            container=~\"rust-client\",\n            status!~\"[4-5].*\"\n        }[30s])) by (container) /\nsum(\n    rate(\n        tester_request_duration_seconds_count\n        {\n            container=~\"rust-client\"\n        }[30s])) by (container)",
     "legendFormat": "Rust"
    }
   ]
  },
  {
   "title": "CPU Throttling",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(container_cpu_cfs_throttled_seconds_total{container_label_io_kubernetes_container_name=\"cpp-app\"}[30s]))",
     "legendFormat": "CPP"
    },
    {
     "expr": "avg(rate(container_cpu_cfs_throttled_seconds_total{container_label_io_kubernetes_container_name=\"rust-app\"}[30s]))",
     "legendFormat": "Rust"
    }
   ]
  }
 ]
}