---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: go-app
  namespace: monitoring
  labels:
    prometheus: main
spec:
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: go-app
  podMetricsEndpoints:
  - port: metrics  # This will match the port name "metrics" in your pod
    path: /metrics
    interval: 15s
