{
 "title": "Performance-v0",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Client Request Latency (p99)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "tester_request_duration_seconds{quantile=\"0.9\", status=\"200\", job=\"monitoring/go-app-client\"}",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "tester_request_duration_seconds{quantile=\"0.9\", status=\"200\", job=\"monitoring/python-app-client\"}",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n    rate(\n        container_cpu_usage_seconds_total{\n            container_label_io_kubernetes_pod_namespace=~\"default\",\n            image!=\"\", \n            container_label_io_cri_containerd_kind=\"container\",\n            container_label_io_kubernetes_container_name!~\".*client.*\",\n            container_label_io_kubernetes_container_name!~\".*minio.*\"\n        }[30s]\n    )\n) by (\n    container_label_io_kubernetes_pod_name, \n    container_label_io_kubernetes_container_name\n) \n/\nsum(\n    container_spec_cpu_quota{\n        container_label_io_kubernetes_pod_namespace=~\"default\",\n        image!=\"\", \n        container_label_io_cri_containerd_kind=\"container\",\n        container_label_io_kubernetes_container_name!~\".*client.*\",\n        container_label_io_kubernetes_container_name!~\".*minio.*\"\n    } \n    / \n    container_spec_cpu_period{\n        container_label_io_kubernetes_pod_namespace=~\"default\", \n        image!=\"\", \n        container_label_io_cri_containerd_kind=\"container\",\n        container_label_io_kubernetes_container_name!~\".*client.*\",\n        container_label_io_kubernetes_container_name!~\".*minio.*\"\n    }\n) by (\n    container_label_io_kubernetes_pod_name, \n    container_label_io_kubernetes_container_name\n)",
     "legendFormat": "{{container_label_io_kubernetes_container_name}}"
    }
   ]
  },
  {
   "title": "Requests Per Second (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(tester_request_duration_seconds_count{status=\"200\", job=\"monitoring/go-app-client\"}[30s])",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "rate(tester_request_duration_seconds_count{status=\"200\", job=\"monitoring/python-app-client\"}[30s])",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{\n    container_label_io_kubernetes_pod_namespace=~\"default\", \n    container_label_io_cri_containerd_kind=\"container\",\n    container_label_io_kubernetes_container_name!~\".*client.*\",\n    container_label_io_kubernetes_container_name!~\".*minio.*\"\n} \n/\ncontainer_spec_memory_limit_bytes{\n    container_label_io_kubernetes_pod_namespace=~\"default\",\n    container_label_io_cri_containerd_kind=\"container\",\n    container_label_io_kubernetes_container_name!~\".*client.*\",\n    container_label_io_kubernetes_container_name!~\".*minio.*\"\n}",
     "legendFormat": "{{container_label_io_kubernetes_container_name}}"
    }
   ]
  }
 ]
}