---
apiVersion: v1
kind: ConfigMap
metadata:
  name: python-app
  namespace: default
data:
  config.yaml: |
    ---
    appPort: 8000
    otlpEndpoint: tempo.monitoring:4317
    s3:
      region: us-west-rack1
      bucket: images
      endpoint: http://192.168.50.211:9000
      pathStyle: true
      user: admin
      secret: devops123
    db:
      user: myuser
      password: devops123
      host: "10.0.49.59"
      database: mydb
