---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpp-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpp-app
  template:
    metadata:
      labels:
        app: cpp-app
    spec:
      # nodeSelector:
      #   node: node-00
      containers:
      - name: cpp-app
        image: dhairya13703/drogon-app:v2
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
        # - name: metrics
        #   containerPort: 8085
        resources:
          requests:
            memory: 512Mi
            cpu: 500m
          limits:
            memory: 512Mi
            cpu: 500m
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
          periodSeconds: 1
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
          periodSeconds: 1
        