---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cpp-app
  namespace: monitoring
  labels:
    prometheus: main
spec:
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: cpp-app
  podMetricsEndpoints:
  - port: metrics
