apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-client
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-client
  template:
    metadata:
      labels:
        app: node-client
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: node-client
        image: aputra/load-tester:v26
        env:
        - name: TEST_URL
          value: "http://node-app.default.svc.cluster.local:8080/api/devices"
        ports:
        - name: metrics
          containerPort: 8085
        resources:
          requests:
            memory: 512Mi
            cpu: 1000m
          limits:
            memory: 512Mi
            cpu: 1000m
        volumeMounts:
        - name: config
          mountPath: Tester.toml
          subPath: Tester.toml
        - name: tls
          mountPath: /ca.pem
          subPath: tls.crt
      volumes:
      - name: config
        configMap:
          name: config-client
      - name: tls
        secret:
          secretName: my-ca
