---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: rust-client
  namespace: monitoring
  labels:
    prometheus: main
spec:
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: rust-client
  podMetricsEndpoints:
  - port: metrics
